package enums;

public enum StatusPayments {
  PENDING_CONFIRMATION,
  CONFIRMED,
  AUTHENTICATION_ERROR,
  ERROR_ROUTING_MUST_BE_9,
  INVALID_FIELD_RECEIVED_ROUTINGNUMBER,
  INTERNAL_SERVER_ERROR,
  INVALID_IP_320921283

}
